PKGDIR          ?= .
L4DIR           ?= $(PKGDIR)/../..

TARGET                   = hacky-bye-server
REQUIRES_LIBS := libc_be_mem libio-io
SRC_CC_hacky-bye-server = server.cc
#SRC_CC_hacky-bye-client = client.cc

include $(L4DIR)/mk/prog.mk

