PKGDIR ?= .
L4DIR ?= $(PKGDIR)/../..

TARGET = hacky hacky-test
REQUIRES_LIBS := libc_be_mem libio-io libpthread libstdc++
SRC_CC_hacky = hacky.cc
SRC_CC_hacky-test = hacky-test.cc

include $(L4DIR)/mk/prog.mk
