PKGDIR ?= .
L4DIR ?= $(PKGDIR)/../..

TARGET = keyboard keytest
REQUIRES_LIBS := libc_be_mem libio-io libpthread libstdc++
SRC_CC_keyboard = keyboard.cc
SRC_CC_keytest = keytest.cc

include $(L4DIR)/mk/prog.mk
